version: '3'
services:
# ------------------------------------------------------------
# Limited use DB (Postgres Server)
# ------------------------------------------------------------
  flectra-db:
     image: postgres:9.6.20
     container_name: flectra-db
     restart: unless-stopped
     volumes:
      - flectra-db:/var/lib/postgresql/data
     environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=flectra
        - POSTGRES_PASSWORD=flectra
# ------------------------------------------------------------
# Flectra instance
# ------------------------------------------------------------
  flectra-app:
    image: flectrahq/flectra
    container_name: flectra-app
    restart: unless-stopped
    volumes:
    - flectra-addons:/mnt/extra-addons
    ports:
    - "7073:7073"
    environment:
      - HOST=flectra-db
# ------------------------------------------------------------
# Axelor instance
# ------------------------------------------------------------
  axelor:
     image: axelor/aio-erp
     container_name: axelor
     restart: unless-stopped
     volumes:
      - axelor-tomcat-lib:/var/lib/tomcat
      - axelor-postgres-lib:/var/lib/postgresql/data
      - axelor-tomcat-log:/var/log/tomcat
      - axelor-postgres-log:/var/log/postgresql
     ports:
      - 9880:80
      - 9881:443
      - 9882:8080
     environment:
        - NGINX_HOST=localhost
        - NGINX_PORT=80
        - POSTGRES_DB=axelor
        - POSTGRES_USER=axelor
        - POSTGRES_PASSWORD=axelor
  
volumes:
  flectra-addons:
  flectra-db:
  axelor-tomcat-lib:
  axelor-postgres-lib:
  axelor-tomcat-log:
  axelor-postgres-log:

