version: '3'
services:
# ------------------------------------------------------------
# Limited use DB (Postgres Server)
# ------------------------------------------------------------
  flectra-db:
     image: postgres:9.6.20
     container_name: flectra-db
     restart: unless-stopped
     volumes:
      - flectra-db:/var/lib/postgresql/data
     environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=flectra
        - POSTGRES_PASSWORD=flectra
# ------------------------------------------------------------
# Flectra instance
# ------------------------------------------------------------
  flectra-app:
    image: flectrahq/flectra
    container_name: flectra-app
    restart: unless-stopped
    volumes:
    - flectra-addons:/mnt/extra-addons
    ports:
    - "7073:7073"
    environment:
      - HOST=flectra-db
volumes:
  flectra-addons:
  flectra-db:

